<%@ page import="in.co.rays.project_3.dto.ReportModuleDTO" %>
<%@ page import="java.util.List" %>

<html>
<head>
<title>Report List</title>
</head>
<body>

<h2>Report List</h2>

<table border="1" width="100%">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>Date</th>
    <th>Generated By</th>
    <th>Status</th>
    <th>Action</th>
</tr>

<%
    List list = (List) request.getAttribute("list");

    if (list != null) {
        for (Object o : list) {
            ReportModuleDTO dto = (ReportModuleDTO) o;
%>
<tr>
    <td><%=dto.getReportId()%></td>
    <td><%=dto.getReportName()%></td>
    <td><%=dto.getGeneratedDate()%></td>
    <td><%=dto.getGeneratedBy()%></td>
    <td><%=dto.getReportStatus()%></td>
    <td>
        <a href="ReportModuleCtl?id=<%=dto.getReportId()%>">Edit</a> |
        <a href="ReportModuleCtl?id=<%=dto.getReportId()%>&operation=DELETE"
           onclick="return confirm('Are you sure you want to delete this record?');">
           Delete
        </a>
    </td>
</tr>
<%
        }
    }
%>

</table>

</body>
</html>
