<%@page import="in.co.rays.project_3.dto.ReportModuleDTO"%>
<%@page import="in.co.rays.project_3.controller.ReportModuleCtl"%>
<%@page import="in.co.rays.project_3.util.DataUtility"%>
<%@page import="in.co.rays.project_3.util.ServletUtility"%>

<html>
<head>
<title>Report Module</title>
</head>
<body>

<%
    ReportModuleDTO dto = (ReportModuleDTO) request.getAttribute("dto");
    if (dto == null) {
        dto = new ReportModuleDTO();
    }
%>

<h2>Report Module</h2>

<font color="green"><%=ServletUtility.getSuccessMessage(request)%></font>

<form action="ReportModuleCtl" method="post">

<input type="hidden" name="reportId" value="<%=dto.getReportId()%>">

<table>
<tr>
    <td>Report Name :</td>
    <td><input type="text" name="reportName" value="<%=dto.getReportName()%>"></td>
</tr>

<tr>
    <td>Generated Date :</td>
    <td><input type="date" name="generatedDate"></td>
</tr>

<tr>
    <td>Generated By :</td>
    <td><input type="text" name="generatedBy" value="<%=dto.getGeneratedBy()%>"></td>
</tr>

<tr>
    <td>Status :</td>
    <td>
        <select name="reportStatus">
            <option value="ACTIVE">ACTIVE</option>
            <option value="INACTIVE">INACTIVE</option>
        </select>
    </td>
</tr>

<tr>
    <td colspan="2">
        <input type="submit" name="operation" value="SAVE">
        <input type="submit" name="operation" value="UPDATE">
    </td>
</tr>
</table>

</form>
</body>
</html>
